#
# Decramble tabdiff-scrambled stuff.
# 
# N.B. The tabdiff scramble isn't entirely reversible. 
#      -  Uppercase letters are mapped to uppercase letters
#      -  Lowercase letters are mapped to (different) uppercase letters
#      -  Both | and } are mapped to | (to ensure that } will be a
#         safe separator for data and loader files).
#
#      The alternative mappings are commented out.

function descram_init () {
descram_map[sprintf("%c",0)] = sprintf("%c",0)
descram_map[sprintf("%c",1)] = sprintf("%c",1)
descram_map[sprintf("%c",2)] = sprintf("%c",2)
descram_map[sprintf("%c",3)] = sprintf("%c",3)
descram_map[sprintf("%c",4)] = sprintf("%c",4)
descram_map[sprintf("%c",5)] = sprintf("%c",5)
descram_map[sprintf("%c",6)] = sprintf("%c",6)
descram_map[sprintf("%c",7)] = sprintf("%c",7)
descram_map[sprintf("%c",8)] = sprintf("%c",8)
descram_map[sprintf("%c",9)] = sprintf("%c",9)
descram_map[sprintf("%c",10)] = sprintf("%c",10)
descram_map[sprintf("%c",11)] = sprintf("%c",11)
descram_map[sprintf("%c",12)] = sprintf("%c",12)
descram_map[sprintf("%c",13)] = sprintf("%c",13)
descram_map[sprintf("%c",14)] = sprintf("%c",14)
descram_map[sprintf("%c",15)] = sprintf("%c",15)
descram_map[sprintf("%c",16)] = sprintf("%c",16)
descram_map[sprintf("%c",17)] = sprintf("%c",17)
descram_map[sprintf("%c",18)] = sprintf("%c",18)
descram_map[sprintf("%c",19)] = sprintf("%c",19)
descram_map[sprintf("%c",20)] = sprintf("%c",20)
descram_map[sprintf("%c",21)] = sprintf("%c",21)
descram_map[sprintf("%c",22)] = sprintf("%c",22)
descram_map[sprintf("%c",23)] = sprintf("%c",23)
descram_map[sprintf("%c",24)] = sprintf("%c",24)
descram_map[sprintf("%c",25)] = sprintf("%c",25)
descram_map[sprintf("%c",26)] = sprintf("%c",26)
descram_map[sprintf("%c",27)] = sprintf("%c",27)
descram_map[sprintf("%c",28)] = sprintf("%c",28)
descram_map[sprintf("%c",29)] = sprintf("%c",29)
descram_map[sprintf("%c",30)] = sprintf("%c",30)
descram_map[sprintf("%c",31)] = sprintf("%c",31)
descram_map[sprintf("%c",32)] = sprintf("%c",32)
descram_map[sprintf("%c",33)] = sprintf("%c",45)
descram_map[sprintf("%c",34)] = sprintf("%c",44)
descram_map[sprintf("%c",35)] = sprintf("%c",39)
descram_map[sprintf("%c",36)] = sprintf("%c",38)
descram_map[sprintf("%c",37)] = sprintf("%c",33)
descram_map[sprintf("%c",38)] = sprintf("%c",46)
descram_map[sprintf("%c",39)] = sprintf("%c",43)
descram_map[sprintf("%c",40)] = sprintf("%c",40)
descram_map[sprintf("%c",41)] = sprintf("%c",37)
descram_map[sprintf("%c",42)] = sprintf("%c",34)
descram_map[sprintf("%c",43)] = sprintf("%c",47)
descram_map[sprintf("%c",44)] = sprintf("%c",42)
descram_map[sprintf("%c",45)] = sprintf("%c",41)
descram_map[sprintf("%c",46)] = sprintf("%c",36)
descram_map[sprintf("%c",47)] = sprintf("%c",35)
descram_map[sprintf("%c",48)] = sprintf("%c",57)
descram_map[sprintf("%c",49)] = sprintf("%c",54)
descram_map[sprintf("%c",50)] = sprintf("%c",53)
descram_map[sprintf("%c",51)] = sprintf("%c",48)
descram_map[sprintf("%c",52)] = sprintf("%c",55)
descram_map[sprintf("%c",53)] = sprintf("%c",52)
descram_map[sprintf("%c",54)] = sprintf("%c",49)
descram_map[sprintf("%c",55)] = sprintf("%c",56)
descram_map[sprintf("%c",56)] = sprintf("%c",51)
descram_map[sprintf("%c",57)] = sprintf("%c",50)
descram_map[sprintf("%c",58)] = sprintf("%c",61)
descram_map[sprintf("%c",59)] = sprintf("%c",58)
descram_map[sprintf("%c",60)] = sprintf("%c",62)
descram_map[sprintf("%c",61)] = sprintf("%c",64)
descram_map[sprintf("%c",62)] = sprintf("%c",63)
descram_map[sprintf("%c",63)] = sprintf("%c",60)
descram_map[sprintf("%c",64)] = sprintf("%c",59)
#descram_map[sprintf("%c",65)] = sprintf("%c",116)
descram_map[sprintf("%c",65)] = sprintf("%c",90)
#descram_map[sprintf("%c",66)] = sprintf("%c",111)
descram_map[sprintf("%c",66)] = sprintf("%c",85)
#descram_map[sprintf("%c",67)] = sprintf("%c",110)
descram_map[sprintf("%c",67)] = sprintf("%c",84)
#descram_map[sprintf("%c",68)] = sprintf("%c",101)
descram_map[sprintf("%c",68)] = sprintf("%c",75)
#descram_map[sprintf("%c",69)] = sprintf("%c",100)
descram_map[sprintf("%c",69)] = sprintf("%c",74)
#descram_map[sprintf("%c",70)] = sprintf("%c",117)
descram_map[sprintf("%c",70)] = sprintf("%c",65)
#descram_map[sprintf("%c",71)] = sprintf("%c",112)
descram_map[sprintf("%c",71)] = sprintf("%c",86)
#descram_map[sprintf("%c",72)] = sprintf("%c",109)
descram_map[sprintf("%c",72)] = sprintf("%c",83)
#descram_map[sprintf("%c",73)] = sprintf("%c",102)
descram_map[sprintf("%c",73)] = sprintf("%c",76)
descram_map[sprintf("%c",74)] = sprintf("%c",73)
#descram_map[sprintf("%c",74)] = sprintf("%c",99)
#descram_map[sprintf("%c",75)] = sprintf("%c",118)
descram_map[sprintf("%c",75)] = sprintf("%c",66)
#descram_map[sprintf("%c",76)] = sprintf("%c",113)
descram_map[sprintf("%c",76)] = sprintf("%c",87)
#descram_map[sprintf("%c",77)] = sprintf("%c",108)
descram_map[sprintf("%c",77)] = sprintf("%c",82)
#descram_map[sprintf("%c",78)] = sprintf("%c",103)
descram_map[sprintf("%c",78)] = sprintf("%c",77)
descram_map[sprintf("%c",79)] = sprintf("%c",72)
#descram_map[sprintf("%c",79)] = sprintf("%c",98)
#descram_map[sprintf("%c",80)] = sprintf("%c",119)
descram_map[sprintf("%c",80)] = sprintf("%c",67)
#descram_map[sprintf("%c",81)] = sprintf("%c",114)
descram_map[sprintf("%c",81)] = sprintf("%c",88)
#descram_map[sprintf("%c",82)] = sprintf("%c",107)
descram_map[sprintf("%c",82)] = sprintf("%c",81)
#descram_map[sprintf("%c",83)] = sprintf("%c",104)
descram_map[sprintf("%c",83)] = sprintf("%c",78)
descram_map[sprintf("%c",84)] = sprintf("%c",71)
#descram_map[sprintf("%c",84)] = sprintf("%c",97)
#descram_map[sprintf("%c",85)] = sprintf("%c",120)
descram_map[sprintf("%c",85)] = sprintf("%c",68)
#descram_map[sprintf("%c",86)] = sprintf("%c",115)
descram_map[sprintf("%c",86)] = sprintf("%c",89)
#descram_map[sprintf("%c",87)] = sprintf("%c",106)
descram_map[sprintf("%c",87)] = sprintf("%c",80)
#descram_map[sprintf("%c",88)] = sprintf("%c",105)
descram_map[sprintf("%c",88)] = sprintf("%c",79)
#descram_map[sprintf("%c",89)] = sprintf("%c",122)
descram_map[sprintf("%c",89)] = sprintf("%c",70)
#descram_map[sprintf("%c",90)] = sprintf("%c",121)
descram_map[sprintf("%c",90)] = sprintf("%c",69)
descram_map[sprintf("%c",91)] = sprintf("%c",95)
descram_map[sprintf("%c",92)] = sprintf("%c",94)
descram_map[sprintf("%c",93)] = sprintf("%c",91)
descram_map[sprintf("%c",94)] = sprintf("%c",96)
descram_map[sprintf("%c",95)] = sprintf("%c",93)
descram_map[sprintf("%c",96)] = sprintf("%c",92)
descram_map[sprintf("%c",123)] = sprintf("%c",123)
descram_map[sprintf("%c",124)] = sprintf("%c",124)
#descram_map[sprintf("%c",123)] = sprintf("%c",125)
descram_map[sprintf("%c",126)] = sprintf("%c",126)
descram_map[sprintf("%c",127)] = sprintf("%c",127)
    return
}
function descramble( to_descram, dlen, di, ret)
{
    dlen = length(to_descram)
    ret = "" 
    for (di = 1; di <= dlen; di++)
        ret = ret descram_map[substr(to_descram,di,1)]
    return ret
}
